import { CoachingObjective, COACHING_RULESET_VERSION } from "./coachingTypes";
import { HypothesisCode, hypothesisCodes } from "./technicalHypothesisCatalog";
export interface RecommendationDefinition {code:string;hypothesisCodes:HypothesisCode[];title:string;rationale:string;objective:CoachingObjective;instruction:string}
const groups:Array<{code:string;codes:HypothesisCode[];title:string;rationale:string;objective:CoachingObjective;instruction:string}>=[
 {code:"REC_TRIGGER_AXIS",codes:["LATERAL_TRIGGER_PRESSURE"],title:"Pression directionnellement neutre",rationale:"Le test a renforcé une hypothèse de composante latérale parasite dans l’action de l’index.",objective:"horizontal_stability",instruction:"Conserver le guidon stable pendant une action de l’index directionnellement neutre, sans composante latérale parasite."},
 {code:"REC_ANTICIPATION",codes:["SHOT_ANTICIPATION"],title:"Accepter le départ sans anticiper",rationale:"Le test temporel a renforcé une réponse anticipatrice possible avant le départ attendu.",objective:"consistency",instruction:"Poursuivre l’action normalement et laisser le départ survenir sans chercher à le provoquer ni à y répondre."},
 {code:"REC_GRIP_CONSTANCY",codes:hypothesisCodes.slice(13,21).filter(code=>!["UNBALANCED_HAND_PRESSURE","WRIST_INSTABILITY","POOR_RECOIL_RETURN","GRIP_CHANGES_BETWEEN_SHOTS"].includes(code)),title:"Prise constante",rationale:"Le test a renforcé une hypothèse de tenue.",objective:"consistency",instruction:"Reproduire la même prise et maintenir le poignet pendant et après le départ."},
 {code:"REC_WRIST_ORGANIZATION",codes:["WRIST_INSTABILITY"],title:"Stabiliser l’organisation du poignet",rationale:"L’observation technique a mis en évidence une rupture parasite reproductible du poignet.",objective:"consistency",instruction:"Reproduire une organisation fonctionnelle comparable du poignet sans chercher à bloquer le recul."},
 {code:"REC_RETURN_TO_LINE",codes:["POOR_RECOIL_RETURN"],title:"Reproduire un retour en ligne cohérent",rationale:"Le test a mis en évidence un retour variable ou une correction musculaire importante et reproductible.",objective:"consistency",instruction:"Conserver l’organisation du poignet, laisser le recul se produire et observer un retour comparable sans correction volontaire excessive."},
 {code:"REC_VISUAL_CONSTANCY",codes:hypothesisCodes.slice(21,27).filter(code=>!["SIGHT_ALIGNMENT_VARIATION","SIGHT_PICTURE_VARIATION","EXCESSIVE_AIMING_TIME"].includes(code)),title:"Repère visuel constant",rationale:"Le test a renforcé une hypothèse de focus visuel.",objective:"dispersion",instruction:"Conserver un repère visuel constant et accepter une zone de mouvement raisonnable."},
 {code:"REC_SIGHT_ALIGNMENT_REPRODUCIBILITY",codes:["SIGHT_ALIGNMENT_VARIATION"],title:"Reconstruire un alignement constant",rationale:"Le test a mis en évidence une variation reproductible de la relation géométrique entre les organes de visée.",objective:"consistency",instruction:"Quitter puis reconstruire plusieurs fois la visée en recherchant une relation géométrique comparable entre les organes de visée."},
 {code:"REC_STABILITY",codes:hypothesisCodes.slice(27,33).filter(code=>!["UNSTABLE_STANCE","INCONSISTENT_BODY_POSITION","POSTURAL_SWAY"].includes(code)),title:"Pointage naturel et stabilité",rationale:"Le test a renforcé une hypothèse de position.",objective:"centering",instruction:"Rechercher une position stable, une tête constante et réduire les tensions inutiles."},
 {code:"REC_CADENCE",codes:hypothesisCodes.slice(33,39).filter(code=>code!=="LOSS_OF_TECHNIQUE_DURING_SERIES"),title:"Cadence régulière",rationale:"Le test a renforcé une hypothèse de séquence.",objective:"consistency",instruction:"Séparer chaque coup et attendre une récupération complète."},
 {code:"REC_EQUIPMENT_CHECK",codes:["EQUIPMENT_OR_SIGHT_ISSUE","UNFAMILIAR_EQUIPMENT"],title:"Configuration à faire vérifier",rationale:"Le résultat reste compatible avec un facteur de configuration ou de matériel.",objective:"centering",instruction:"Vérifier la saisie de l’arme, de la cible et de la distance ; demander une vérification qualifiée si nécessaire."},
 {code:"REC_TWO_HAND_COORDINATION",codes:["TWO_HAND_CONTRIBUTION"],title:"Coordonner la contribution des deux mains",
  rationale:"Le test comparatif indique que la contribution relative des deux mains modifie de manière reproductible le comportement de l’arme.",
  objective:"consistency",instruction:"Retrouver une organisation des deux mains qui stabilise l’arme sans créer de perturbation parasite identifiable, sans rechercher de ratio universel."},
];
export const coachingRecommendationCatalog:RecommendationDefinition[]=groups.map(({codes,...x})=>({...x,hypothesisCodes:codes}));
