import { ConfirmationTestDefinition, COACHING_RULESET_VERSION } from "./coachingTypes";
import { DRY_FIRE_SAFETY, LIVE_FIRE_SAFETY } from "./coachingSafetyRules";

const dry=(code:string,title:string,objective:string,hypothesisCodes:ConfirmationTestDefinition["hypothesisCodes"],
 observationCriteria:string[],discriminatesAgainst:ConfirmationTestDefinition["discriminatesAgainst"]=[]):ConfirmationTestDefinition=>({
 code,title,objective,hypothesisCodes,category: categoryFor(code),prerequisites:["Contexte calme et consigne comprise."],
 safetyRequirements:DRY_FIRE_SAFETY,instructions:["Préparer la zone à sec.","Effectuer cinq départs attentifs sans rechercher de vitesse.","Noter uniquement ce qui est observé."],
 observationCriteria,possibleOutcomes:["supports_hypothesis","weakly_supports_hypothesis","does_not_support_hypothesis","contradicts_hypothesis","inconclusive","not_observed"],
 minimumDuration:2,maximumDuration:5,requiresLiveFire:false,requiresDryFire:true,requiresDummyRounds:false,
 requiresInstructor:false,supportedWeaponTypes:["semi_automatic_pistol"],supportedSessionModes:["coaching_free","training"],
 discriminatesAgainst,rulesetVersion:COACHING_RULESET_VERSION});
function categoryFor(code:string):ConfirmationTestDefinition["category"]{
 if(code.includes("TWO_HAND"))return "grip";
 if(code.includes("TRIGGER")||code.includes("FINGER"))return"trigger";if(code.includes("ANTICIPATION")||code.includes("FLINCH"))return"anticipation";
 if(code.includes("GRIP")||code.includes("RETURN")||code.includes("WRIST"))return"grip";if(code.includes("FOCUS")||code.includes("AIM"))return"vision";
 if(code.includes("POINT")||code.includes("STANCE"))return"stability";if(code.includes("CADENCE")||code.includes("SLOW"))return"cadence";
 return"context_equipment";
}
export const confirmationTestCatalog:ConfirmationTestDefinition[]=[
 {...dry("TEST_TRIGGER_FINGER_PLACEMENT","Placement descriptif du doigt","Vérifier si une légère modification du placement réduit le mouvement parasite, sans imposer une position universelle.",
  ["TRIGGER_FINGER_TOO_LITTLE","TRIGGER_FINGER_TOO_DEEP","LATERAL_TRIGGER_PRESSURE"],
  ["Pression dans l’axe sans déplacement visible","Déplacement répétitif selon le placement","Aucune différence observable"]),
  instructions:["Préparer la zone à sec.",
   "Effectuer des départs avec le placement habituel et observer le mouvement des organes de visée.",
   "Modifier légèrement le placement de l’index, sans rechercher une profondeur universelle, puis répéter les départs.",
   "Comparer uniquement si le mouvement parasite diminue, disparaît ou reste inchangé."]},
 dry("TEST_SIGHT_STABILITY_DRY","Stabilité du guidon à sec","Observer un déplacement au départ.",
  ["LATERAL_TRIGGER_PRESSURE"],
  ["Guidon stable","Mouvement latéral répétitif","Mouvement vertical","Mouvement variable","Résultat non observable"],
  ["EQUIPMENT_OR_SIGHT_ISSUE"]),
 dry("TEST_ANTICIPATION_DRY","Départ attendu non produit","Observer si une réponse motrice apparaît avant ou au moment du départ attendu alors qu’aucun recul réel ne survient.",
  ["SHOT_ANTICIPATION"],
  ["Aucune réaction anticipatrice observable","Abaissement anticipé reproductible","Poussée anticipée reproductible","Sursaut ou crispation anticipatrice reproductible","Fermeture des yeux anticipatrice reproductible","Autre réponse anticipatrice reproductible","Résultat non observable ou ambigu"]),
 dry("TEST_GRIP_CONSTANCY","Constance de prise","Vérifier si la prise change entre les répétitions.",
  ["WEAK_SUPPORT_HAND_PRESSURE","EXCESSIVE_SUPPORT_HAND_PRESSURE","INCONSISTENT_GRIP_PRESSURE"],
  ["Prise ressentie constante","Crispation croissante","Pression variable","Changement de placement"]),
 {...dry("TEST_TWO_HAND_CONTRIBUTION","Test comparatif de contribution des deux mains",
  "Déterminer si une modification contrôlée de la contribution relative des deux mains modifie de manière reproductible la perturbation observée.",
  ["TWO_HAND_CONTRIBUTION"],
  ["Amélioration reproductible","Dégradation reproductible","Aucune différence observable","Résultat variable ou non interprétable"]),
  instructions:["Préparer la zone à sec et conserver autant que possible la posture, la visée, l’action sur la détente, la cadence et le placement général des mains.",
   "Configuration A : effectuer plusieurs départs avec la prise habituelle et observer uniquement le comportement de l’arme.",
   "Configuration B : augmenter légèrement la contribution de la main de support, sans pourcentage ni force cible, puis répéter dans les mêmes conditions.",
   "Comparer uniquement si l’effet est reproductible, sans conclure qu’une main est trop forte ou trop faible."],
  prerequisites:["Séance réalisée à deux mains.","Contexte calme et consigne comprise."]},
 {...dry("TEST_TRIGGER_HAND_INDEPENDENCE","Test d’indépendance index–main",
  "Observer directement si les autres doigts de la main qui tient l’arme modifient leur action de façon synchronisée avec l’index.",
  ["TRIGGER_FINGER_HAND_COACTIVATION"],
  ["Autres doigts sensiblement stables pendant l’action de l’index",
   "Augmentation reproductible de leur action ou pression synchronisée avec l’index",
   "Relâchement reproductible synchronisé avec l’index","Comportement variable ou non observable de manière fiable"]),
  instructions:["Préparer la zone à sec et installer la prise normalement.",
   "Réaliser plusieurs actions contrôlées de l’index sans rechercher de départ rapide.",
   "Observer directement les autres doigts de la main qui tient l’arme, sans utiliser les impacts ni la seule stabilité du guidon comme preuve.",
   "Retenir uniquement un comportement reproductible et synchronisé avec l’action de l’index."],
  prerequisites:["Contexte calme et consigne comprise.","Les autres doigts de la main qui tient l’arme doivent être directement observables."],
  discriminatesAgainst:["LATERAL_TRIGGER_PRESSURE","INCONSISTENT_TRIGGER_PRESS","ABRUPT_TRIGGER_PRESS"]},
 dry("TEST_WRIST_STABILITY","Test de stabilité du poignet","Observer directement si le poignet conserve une organisation stable pendant l’action et le départ.",
  ["WRIST_INSTABILITY"],["Organisation sensiblement stable","Flexion ou rupture parasite reproductible","Variation irrégulière","Non observable de manière fiable"]),
 {...dry("TEST_RETURN_TO_LINE","Retour en ligne","Observer si l’arme revient de manière reproductible vers une position comparable, sans correction musculaire importante ou variable.",
  ["POOR_RECOIL_RETURN","INSUFFICIENT_RECOVERY_BETWEEN_SHOTS"],["Retour régulier et comparable","Retour variable d’un coup à l’autre","Correction musculaire importante nécessaire","Retour systématiquement décalé mais reproductible","Non observable de manière fiable"]),
  requiresDryFire:false,requiresLiveFire:true,safetyRequirements:LIVE_FIRE_SAFETY,instructions:["Au stand autorisé, tirer une série lente de cinq coups.","Après chaque coup, observer le retour sans accélérer."]},
 dry("TEST_VISUAL_FOCUS","Focalisation","Identifier ce qui reste net au départ.",
  ["FOCUS_ON_TARGET_INSTEAD_OF_SIGHTS","INCONSISTENT_VISUAL_FOCUS","LOSS_OF_VISUAL_FOCUS_AT_SHOT"],
  ["Repère visuel constant","Focalisation changeante","Perte du guidon au départ","Non observable"]),
 dry("TEST_SIGHT_ALIGNMENT_REPRODUCIBILITY","Test de reproductibilité de l’alignement","Observer si la même relation géométrique entre les organes de visée est reconstruite d’une répétition à l’autre.",
  ["SIGHT_ALIGNMENT_VARIATION"],["Alignement reproduit de manière comparable","Variation latérale reproductible de l’alignement","Variation verticale reproductible de l’alignement","Variation irrégulière ou non interprétable","Alignement non observable de manière fiable"]),
 dry("TEST_AIMING_DURATION","Durée de visée","Vérifier si la stabilité se dégrade quand la visée est maintenue.",
  ["AIMING_ZONE_TOO_RESTRICTED"],["Stabilité conservée","Dégradation après plusieurs secondes","Départ forcé"]),
 dry("TEST_NATURAL_POINT","Pointage naturel","Vérifier le retour vers la zone visée sans correction musculaire excessive.",
  ["POOR_NATURAL_POINT_OF_AIM","SHOULDER_TENSION"],
  ["Retour naturel vers la zone","Décalage répété","Correction musculaire marquée"]),
 {...dry("TEST_SLOW_CONTROLLED_SERIES","Série lente contrôlée","Comparer la qualité des premiers et derniers impacts.",
  ["CADENCE_TOO_FAST","RUSHED_FOLLOW_UP_SHOTS"],["Qualité stable","Dégradation en fin de série","Amélioration à cadence lente"]),
  requiresDryFire:false,requiresLiveFire:true,safetyRequirements:LIVE_FIRE_SAFETY,instructions:["Au stand autorisé, tirer cinq coups lents.","Séparer clairement chaque séquence."]},
 {...dry("TEST_REGULAR_CADENCE","Cadence régulière","Observer l’effet d’une cadence régulière sans précipitation.",
  ["CADENCE_IRREGULAR","INSUFFICIENT_RECOVERY_BETWEEN_SHOTS","EXCESSIVE_TIME_BETWEEN_SHOTS"],["Cadence et qualité stables","Précipitation","Pauses irrégulières"]),
  requiresDryFire:false,requiresLiveFire:true,safetyRequirements:LIVE_FIRE_SAFETY},
 {code:"TEST_DUMMY_ROUND_SUPERVISED",hypothesisCodes:["SHOT_ANTICIPATION"],
  category:"anticipation",title:"Alternance réelle/inerte supervisée",objective:"Observer une réaction au départ dans un cadre autorisé.",
  prerequisites:["Stand autorisant la procédure.","Tireur connaissant la procédure."],safetyRequirements:LIVE_FIRE_SAFETY,
  instructions:["Test réservé à un cadre supervisé et sécurisé.","Aucun chargement secret par un tiers hors de ce cadre."],
  observationCriteria:["Mouvement observé sur cartouche inerte","Aucun mouvement","Résultat non observable"],
  possibleOutcomes:["supports_hypothesis","does_not_support_hypothesis","inconclusive","not_observed"],minimumDuration:3,maximumDuration:8,
  requiresLiveFire:true,requiresDryFire:false,requiresDummyRounds:true,requiresInstructor:true,
  supportedWeaponTypes:["semi_automatic_pistol"],supportedSessionModes:["coaching_free","training"],
  discriminatesAgainst:["EQUIPMENT_OR_SIGHT_ISSUE"],rulesetVersion:COACHING_RULESET_VERSION},
 {code:"TEST_EQUIPMENT_CONTEXT_CHECK",hypothesisCodes:["EQUIPMENT_OR_SIGHT_ISSUE","UNFAMILIAR_EQUIPMENT"],
  category:"context_equipment",title:"Vérification de configuration",
  objective:"Vérifier si le décalage observé peut être expliqué par un élément de configuration avant de conclure à une cause technique du tireur.",
  prerequisites:["Les conditions réelles de la série et les données saisies doivent pouvoir être consultées."],
  safetyRequirements:["Respecter les règles générales de sécurité pendant toute vérification visuelle.",
   "Ne modifier aucun organe de visée ni aucun élément matériel sans vérification qualifiée."],
  instructions:[
   "Vérifiez que l’arme sélectionnée dans l’application est bien celle utilisée.",
   "Vérifiez la distance et le type de cible.",
   "Confirmez le point réellement visé pendant la série.",
   "Vérifiez visuellement que les organes de visée ne présentent pas d’anomalie évidente ou de modification connue.",
   "Si un doute subsiste sur le réglage ou le matériel, demandez une vérification qualifiée avant de modifier quoi que ce soit.",
  ],
  observationCriteria:["Configuration cohérente","Écart entre saisie et conditions réelles",
   "Point visé différent de celui supposé","Doute sur le réglage ou le matériel",
   "Vérification qualifiée nécessaire","Résultat non concluant"],
  possibleOutcomes:["supports_hypothesis","weakly_supports_hypothesis","does_not_support_hypothesis",
   "contradicts_hypothesis","inconclusive","not_observed"],minimumDuration:2,maximumDuration:5,
  requiresLiveFire:false,requiresDryFire:false,requiresDummyRounds:false,requiresInstructor:false,
  supportedWeaponTypes:["semi_automatic_pistol"],supportedSessionModes:["coaching_free","training"],
  discriminatesAgainst:[],rulesetVersion:COACHING_RULESET_VERSION},
];
