import { COMMON_STOP_CONDITIONS, DRY_FIRE_SAFETY, LIVE_FIRE_SAFETY } from "./coachingSafetyRules";
import { COACHING_RULESET_VERSION, TrainingDrill } from "./coachingTypes";
import { hypothesisCodes } from "./technicalHypothesisCatalog";
const base=(x:Omit<TrainingDrill,"stopConditions"|"rulesetVersion"|"allowedModes"|"difficultyLevel">):TrainingDrill=>({
 ...x,stopConditions:COMMON_STOP_CONDITIONS,rulesetVersion:COACHING_RULESET_VERSION,
 allowedModes:["coaching_free","training"],difficultyLevel:["beginner","intermediate","advanced"]});
export const trainingDrillCatalog:TrainingDrill[]=[
 base({code:"DRILL_DRY_CONTROLLED_RELEASES",linkedHypothesisCodes:hypothesisCodes.slice(0,7),linkedRecommendationCodes:["REC_TRIGGER_AXIS"],title:"Départs à sec contrôlés",objective:"horizontal_stability",preparation:["Préparer une zone à sec."],executionSteps:["Effectuer cinq départs en observant les organes de visée."],numberOfRepetitions:5,numberOfShots:0,pace:"Lent",rest:"Pause courte après cinq répétitions.",successCriteria:["Guidon stable pendant quatre départs sur cinq."],failureCriteria:["Déplacement répétitif visible."],safetyRequirements:DRY_FIRE_SAFETY,requiresLiveFire:false,requiresDryFire:true,requiresDummyRounds:false,requiresInstructor:false}),
 base({code:"DRILL_ACCEPT_DEPARTURE_E1",linkedHypothesisCodes:["SHOT_ANTICIPATION"],linkedRecommendationCodes:["REC_ANTICIPATION"],title:"Laisser partir sans anticiper",objective:"consistency",preparation:["Préparer une zone à sec dans les conditions de sécurité requises."],executionSteps:["Produire l’action normale sans chercher à provoquer l’instant du départ.","Observer directement l’absence de réponse anticipatrice, sans utiliser l’impact comme preuve."],numberOfRepetitions:5,numberOfShots:0,pace:"Contrôlé",rest:"Pause si l’observation devient ambiguë.",successCriteria:["Le tireur répète l’action sans réponse motrice anticipatrice observable."],failureCriteria:["Une réponse anticipatrice reproductible reste présente ou l’observation devient ambiguë."],safetyRequirements:DRY_FIRE_SAFETY,requiresLiveFire:false,requiresDryFire:true,requiresDummyRounds:false,requiresInstructor:false}),
 base({code:"DRILL_SLOW_VALIDATION",linkedHypothesisCodes:hypothesisCodes.slice(0,39).filter(code=>code!=="SIGHT_ALIGNMENT_VARIATION"),linkedRecommendationCodes:["REC_TRIGGER_AXIS","REC_VISUAL_CONSTANCY","REC_STABILITY"],title:"Série lente de validation",objective:"dispersion",preparation:["Choisir une seule consigne."],executionSteps:["Tirer cinq coups lentement en conservant uniquement cette consigne."],numberOfRepetitions:1,numberOfShots:5,pace:"Lent",rest:"Pause après la série.",successCriteria:["Dispersion réduite ou stable sans dégradation finale."],failureCriteria:["Dispersion fortement augmentée."],safetyRequirements:LIVE_FIRE_SAFETY,requiresLiveFire:true,requiresDryFire:false,requiresDummyRounds:false,requiresInstructor:false}),
 base({code:"DRILL_SIGHT_ALIGNMENT_RECONSTRUCTION",linkedHypothesisCodes:["SIGHT_ALIGNMENT_VARIATION"],linkedRecommendationCodes:["REC_SIGHT_ALIGNMENT_REPRODUCIBILITY"],title:"Reconstruire le même alignement",objective:"consistency",preparation:["Préparer une zone à sec et choisir une position de visée neutre."],executionSteps:["Construire la visée, observer la relation géométrique entre les organes de visée, quitter volontairement la visée puis la reconstruire plusieurs fois."],numberOfRepetitions:5,numberOfShots:0,pace:"Contrôlé",rest:"Pause si la qualité d’observation diminue.",successCriteria:["Le tireur reconstruit plusieurs fois une relation géométrique comparable entre les organes de visée, sans variation parasite manifeste."],failureCriteria:["La relation géométrique reste variable ou non interprétable."],safetyRequirements:DRY_FIRE_SAFETY,requiresLiveFire:false,requiresDryFire:true,requiresDummyRounds:false,requiresInstructor:false}),
 base({code:"DRILL_FOLLOW_THROUGH",linkedHypothesisCodes:hypothesisCodes.slice(7,21).filter(code=>!["WRIST_INSTABILITY","POOR_RECOIL_RETURN"].includes(code)),linkedRecommendationCodes:["REC_ANTICIPATION","REC_GRIP_CONSTANCY"],title:"Maintien après le départ",objective:"consistency",preparation:["Une seule consigne : maintenir."],executionSteps:["Conserver prise, visée et attention après chaque départ."],numberOfRepetitions:1,numberOfShots:5,pace:"Lent",rest:"Pause après cinq coups.",successCriteria:["Retour et maintien réguliers sur quatre coups sur cinq."],failureCriteria:["Rupture de prise ou de visée répétée."],safetyRequirements:LIVE_FIRE_SAFETY,requiresLiveFire:true,requiresDryFire:false,requiresDummyRounds:false,requiresInstructor:false}),
 base({code:"DRILL_CONSTANT_GRIP",linkedHypothesisCodes:hypothesisCodes.slice(13,21).filter(code=>!["WRIST_INSTABILITY","POOR_RECOIL_RETURN"].includes(code)),linkedRecommendationCodes:["REC_GRIP_CONSTANCY"],title:"Prise constante",objective:"consistency",preparation:["Repérer une prise confortable et reproductible."],executionSteps:["Reproduire la même prise à chaque coup."],numberOfRepetitions:1,numberOfShots:5,pace:"Contrôlé",rest:"Relâcher entre les séries.",successCriteria:["Pression ressentie comme constante."],failureCriteria:["Crispation ou changement de prise."],safetyRequirements:LIVE_FIRE_SAFETY,requiresLiveFire:true,requiresDryFire:false,requiresDummyRounds:false,requiresInstructor:false}),
 base({code:"DRILL_WRIST_ORGANIZATION",linkedHypothesisCodes:["WRIST_INSTABILITY"],linkedRecommendationCodes:["REC_WRIST_ORGANIZATION"],title:"Reproduire l’organisation du poignet",objective:"consistency",preparation:["Installer une organisation fonctionnelle du poignet sans rigidité excessive."],executionSteps:["Répéter plusieurs actions comparables en observant directement le poignet, sans chercher à empêcher le mouvement normal de l’arme."],numberOfRepetitions:5,numberOfShots:0,pace:"Contrôlé",rest:"Pause si une tension apparaît.",successCriteria:["Le tireur reproduit plusieurs fois une organisation comparable du poignet sans rupture parasite manifeste."],failureCriteria:["Une flexion ou rupture parasite reste reproductible."],safetyRequirements:DRY_FIRE_SAFETY,requiresLiveFire:false,requiresDryFire:true,requiresDummyRounds:false,requiresInstructor:false}),
 base({code:"DRILL_RETURN_TO_LINE",linkedHypothesisCodes:["POOR_RECOIL_RETURN"],linkedRecommendationCodes:["REC_RETURN_TO_LINE"],title:"Reproduire un retour en ligne cohérent",objective:"consistency",preparation:["Visée ouverte clairement visible et organisation fonctionnelle du poignet."],executionSteps:["Laisser le recul se produire et observer plusieurs retours sans correction volontaire excessive."],numberOfRepetitions:1,numberOfShots:5,pace:"Contrôlé",rest:"Pause après cinq coups.",successCriteria:["Le retour devient reproductible et comparable sans correction musculaire excessive ou différente d’un tir à l’autre."],failureCriteria:["Le retour reste variable ou nécessite des corrections importantes différentes."],safetyRequirements:LIVE_FIRE_SAFETY,requiresLiveFire:true,requiresDryFire:false,requiresDummyRounds:false,requiresInstructor:false}),
 base({code:"DRILL_REGULAR_CADENCE",linkedHypothesisCodes:hypothesisCodes.slice(33,39),linkedRecommendationCodes:["REC_CADENCE"],title:"Cadence régulière",objective:"consistency",preparation:["Définir une cadence confortable."],executionSteps:["Tirer cinq coups sans précipitation ni pause excessive."],numberOfRepetitions:1,numberOfShots:5,pace:"Régulier",rest:"Pause complète après la série.",successCriteria:["Aucune dégradation sur les derniers coups."],failureCriteria:["Précipitation ou pauses irrégulières."],safetyRequirements:LIVE_FIRE_SAFETY,requiresLiveFire:true,requiresDryFire:false,requiresDummyRounds:false,requiresInstructor:false}),
 base({code:"DRILL_NATURAL_POINT",linkedHypothesisCodes:hypothesisCodes.slice(27,33),linkedRecommendationCodes:["REC_STABILITY"],title:"Pointage naturel",objective:"centering",preparation:["Position stable, direction sûre."],executionSteps:["Contrôler la cohérence entre position du corps et zone visée."],numberOfRepetitions:5,numberOfShots:0,pace:"Lent",rest:"Repos si tension.",successCriteria:["Retour naturel cohérent vers la zone."],failureCriteria:["Correction musculaire répétée."],safetyRequirements:DRY_FIRE_SAFETY,requiresLiveFire:false,requiresDryFire:true,requiresDummyRounds:false,requiresInstructor:false}),
 base({code:"DRILL_EQUIPMENT_CONTROL",linkedHypothesisCodes:["EQUIPMENT_OR_SIGHT_ISSUE","UNFAMILIAR_EQUIPMENT"],linkedRecommendationCodes:["REC_EQUIPMENT_CHECK"],title:"Série de contrôle après vérification",objective:"centering",preparation:["Faire confirmer la cohérence de la configuration par un instructeur et demander une vérification qualifiée si un doute subsiste, sans modifier automatiquement le matériel."],executionSteps:["Sans modifier volontairement votre technique, réalisez une nouvelle série de 5 coups dans les mêmes conditions après la vérification de configuration."],numberOfRepetitions:1,numberOfShots:5,pace:"Lent",rest:"Pause après la série.",successCriteria:["Le résultat permet de voir si le décalage persiste ou non."],failureCriteria:["Les données ne permettent pas de déterminer si le décalage persiste."],safetyRequirements:LIVE_FIRE_SAFETY,requiresLiveFire:true,requiresDryFire:false,requiresDummyRounds:false,requiresInstructor:true}),
 base({code:"DRILL_TWO_HAND_CONTRIBUTION",linkedHypothesisCodes:["TWO_HAND_CONTRIBUTION"],
  linkedRecommendationCodes:["REC_TWO_HAND_COORDINATION"],title:"Reproduire la contribution efficace des deux mains",
  objective:"consistency",preparation:["Retrouver la configuration ayant donné le comportement le plus stable pendant le test, sans rechercher de ratio de force."],
  executionSteps:["Reproduire plusieurs fois l’organisation efficace des deux mains et vérifier que le comportement de l’arme reste comparable.",
   "Si nécessaire, revenir brièvement à la prise habituelle pour confirmer la différence, puis reprendre la configuration efficace."],
  numberOfRepetitions:1,numberOfShots:5,pace:"Contrôlé",rest:"Pause complète après la série.",
  successCriteria:["Le tireur reproduit plusieurs fois de suite une organisation des deux mains donnant un comportement stable et comparable, sans perturbation parasite manifeste."],
  failureCriteria:["Le comportement reste variable ou la comparaison ne permet pas d’identifier une organisation reproductible."],
  safetyRequirements:LIVE_FIRE_SAFETY,requiresLiveFire:true,requiresDryFire:false,requiresDummyRounds:false,requiresInstructor:false}),
];
